import React, { useState, useRef } from 'react'
import { Sparkles, CheckSquare, ChevronRight, ChevronLeft, GripVertical } from 'lucide-react'
import { useStore } from '../store/useStore'

export const TaskCard = ({ task }) => {
  const { openTaskDrawer, moveTask, columns, theme } = useStore()
  const [isDragging, setIsDragging] = useState(false)
  const isDraggingJustNowRef = useRef(false)

  const isDark = theme === 'dark'

  // Category Color Badges Harmonized for both Dark and Light themes
  const getCategoryStyles = (category) => {
    switch (category?.toLowerCase()) {
      case 'backend':
        return 'bg-teal-500/10 text-teal-400 border-teal-500/30'
      case 'frontend':
        return 'bg-blue-500/10 text-blue-400 border-blue-500/30'
      case 'database':
        return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
      case 'security':
        return 'bg-amber-500/10 text-amber-400 border-amber-500/30'
      case 'ai / llm':
      case 'ai':
        return 'bg-purple-500/10 text-purple-400 border-purple-500/30'
      default:
        return 'bg-slate-500/10 text-slate-400 border-slate-500/30'
    }
  }

  // Priority Color Dot
  const getPriorityDot = (priority) => {
    switch (priority?.toLowerCase()) {
      case 'high':
        return 'bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.6)]'
      case 'medium':
        return 'bg-amber-400'
      case 'low':
        return 'bg-blue-400'
      default:
        return 'bg-slate-400'
    }
  }

  const completedAcCount = task.acceptanceCriteria?.filter((ac) => ac.completed).length || 0
  const totalAcCount = task.acceptanceCriteria?.length || 0
  const progressPercent = totalAcCount > 0 ? (completedAcCount / totalAcCount) * 100 : 0

  // WCAG Single pointer alternative: Move to next or previous column
  const currentColumnIndex = columns.findIndex((c) => c.id === task.columnId)

  const handleMovePrev = (e) => {
    e.stopPropagation()
    if (currentColumnIndex > 0) {
      moveTask(task.id, columns[currentColumnIndex - 1].id)
    }
  }

  const handleMoveNext = (e) => {
    e.stopPropagation()
    if (currentColumnIndex < columns.length - 1) {
      moveTask(task.id, columns[currentColumnIndex + 1].id)
    }
  }

  // Drag Handlers
  const handleDragStart = (e) => {
    isDraggingJustNowRef.current = true
    setIsDragging(true)
    e.dataTransfer.setData('text/plain', task.id)
    e.dataTransfer.effectAllowed = 'move'
  }

  const handleDragEnd = () => {
    setIsDragging(false)
    setTimeout(() => {
      isDraggingJustNowRef.current = false
    }, 150)
  }

  const handleClick = (e) => {
    if (isDraggingJustNowRef.current || isDragging) return
    openTaskDrawer(task.id)
  }

  return (
    <div
      draggable="true"
      onDragStart={handleDragStart}
      onDragEnd={handleDragEnd}
      onClick={handleClick}
      className={`task-card group relative border rounded-xl p-4 transition-all duration-150 cursor-grab active:cursor-grabbing select-none text-left flex flex-col gap-3 shadow-xs hover:shadow-md ${
        isDragging 
          ? 'opacity-40 scale-[0.98] border-dashed border-teal-500 bg-teal-500/10' 
          : isDark 
            ? 'bg-[#090D16] hover:bg-[#172033] border-[#1F293D] hover:border-teal-500/50' 
            : 'bg-white hover:bg-slate-50/90 border-[#E2E8F0] hover:border-teal-500/40'
      }`}
    >
      {/* Top Meta: Badges & AI Tag & Story Points */}
      <div className="flex items-center justify-between gap-1.5">
        <div className="flex items-center gap-1.5 flex-wrap">
          <GripVertical className="w-3.5 h-3.5 text-slate-400 opacity-40 group-hover:opacity-100 transition-opacity shrink-0 -ml-1 cursor-grab" />
          <span className={`text-[11px] font-semibold px-2.5 py-0.5 rounded-lg border ${getCategoryStyles(task.category)}`}>
            {task.category || 'General'}
          </span>
          {task.isAiGenerated && (
            <span className="flex items-center gap-1 text-[10px] text-teal-400 font-mono bg-teal-500/10 border border-teal-500/30 px-2 py-0.5 rounded-lg" title="Generated by Gemini AI">
              <Sparkles className="w-2.5 h-2.5" />
              <span>AI</span>
            </span>
          )}
        </div>

        {/* Story Points */}
        <span className={`text-[11px] font-bold font-mono px-2 py-0.5 rounded-lg border ${
          isDark 
            ? 'bg-[#172033] text-teal-300 border-[#1F293D]' 
            : 'bg-slate-100 text-teal-700 border-slate-200'
        }`}>
          {task.storyPoints || 1} pts
        </span>
      </div>

      {/* Task Title */}
      <h4 className={`text-sm font-semibold group-hover:text-teal-400 leading-snug line-clamp-2 transition-smooth ${
        isDark ? 'text-white' : 'text-slate-900'
      }`}>
        {task.title}
      </h4>

      {/* Acceptance Criteria Mini Progress Bar */}
      {totalAcCount > 0 && (
        <div className="flex flex-col gap-1.5 pt-1">
          <div className={`flex items-center justify-between text-[11px] ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
            <span className="flex items-center gap-1">
              <CheckSquare className="w-3 h-3 text-teal-400" />
              <span>Criteria</span>
            </span>
            <span className="font-mono text-[10px] text-teal-400 font-semibold">
              {completedAcCount}/{totalAcCount} AC
            </span>
          </div>
          <div className={`w-full h-1.5 rounded-full overflow-hidden border ${
            isDark ? 'bg-[#172033] border-[#1F293D]' : 'bg-slate-100 border-slate-200'
          }`}>
            <div
              className="bg-teal-500 h-full rounded-full transition-all duration-300"
              style={{ width: `${progressPercent}%` }}
            />
          </div>
        </div>
      )}

      {/* Bottom Footer: Priority, Assignee & Quick Column Mover */}
      <div className={`flex items-center justify-between pt-2 border-t ${isDark ? 'border-[#1F293D]' : 'border-slate-100'}`}>
        {/* Priority Dot */}
        <div className="flex items-center gap-1.5" title={`Priority: ${task.priority}`}>
          <span className={`w-2 h-2 rounded-full ${getPriorityDot(task.priority)}`}></span>
          <span className={`text-[11px] font-medium ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>{task.priority}</span>
        </div>

        {/* Right side: Single pointer quick mover + Assignee */}
        <div className="flex items-center gap-2">
          {/* Quick Column Shift (WCAG alternative for Drag and Drop) */}
          <div className={`opacity-0 group-hover:opacity-100 flex items-center gap-0.5 transition-smooth p-0.5 rounded-lg border ${
            isDark ? 'bg-[#172033] border-[#1F293D]' : 'bg-slate-100 border-slate-200'
          }`}>
            <button
              onClick={handleMovePrev}
              disabled={currentColumnIndex === 0}
              className="p-1 hover:bg-teal-500/20 disabled:opacity-30 disabled:cursor-not-allowed rounded transition-smooth"
              title="Move to Previous Column"
            >
              <ChevronLeft className="w-3 h-3" />
            </button>
            <button
              onClick={handleMoveNext}
              disabled={currentColumnIndex === columns.length - 1}
              className="p-1 hover:bg-teal-500/20 disabled:opacity-30 disabled:cursor-not-allowed rounded transition-smooth"
              title="Move to Next Column"
            >
              <ChevronRight className="w-3 h-3" />
            </button>
          </div>

          {/* Assignee Avatar */}
          <div className="relative" title={task.assignee?.name || 'Assignee'}>
            <img
              src={task.assignee?.avatar || 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces'}
              alt={task.assignee?.name}
              className={`w-6 h-6 rounded-full border object-cover ${isDark ? 'border-[#1F293D]' : 'border-slate-300'}`}
            />
          </div>
        </div>
      </div>
    </div>
  )
}
